### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by yukuku** [the-glu/telegram_backup#1]
After dumping several chats, dump.py terminates with:

Traceback (most recent call last):
  File "dump.py", line 153, in <module>
    work_on_dialog(d)
  File "dump.py", line 74, in work_on_dialog
    messages[message['id']] = message
TypeError: string indices must be integers

**Comment by the-glu** [comment]
Can you add `print(message['id'])` before line 74 and check the message id ?

If that also fails, can you also add `print(message)` to check the message ?

**Comment by yukuku** [comment]
`print(message['id'])` causes the same error, so I did `print(message)` and the result is `error`. 

What I meant is, the variable `message` contains the string `error`.

**Comment by the-glu** [comment]
Ok, strange. What the content of `last_messages` when message contains error ?

```
if message == "error":
    print(last_messages)
```

Is there any other errors or just normal messages ?

**Comment by yukuku** [comment]
This is the content of `last_messages`:
   `{'error': 'can not parse arg #1', 'result': 'FAIL', 'error_code': 78}`

Looks like somehow the `last_messages` becomes a dict and not a list (I have limited python knowledge)

**Comment by the-glu** [comment]
Ok, I think this is dues to bad escaping of the group name. What does he looks like ? (First line of the logs and in telegram)

**Comment by yukuku** [comment]
After the line

```
logging.info("Working on %s %s %s", d['type'], d['print_name'], d['id'])
```

I added:

```
print(d)
```

So the output now shows:

```
INFO:root:Working on user  67611***
{'flags': 1280, 'print_name': '', 'id': 67611***, 'type': 'user'}
```

Looks like having empty string for print_name is weird..

**Comment by the-glu** [comment]
Ok, it's strange, I assume it's a telegram-cli 'bug' (c.f https://github.com/vysheng/tg/pull/708 , the used was probably deleted)

I added a workaround with a warning, history is probably not retrievable for this user. Can you try again with the latest version ?

**Comment by yukuku** [comment]
With warning, it now works. Now there is another exception, I will submit another issue  (#3)

**Comment by the-glu** [comment]
Ok, thanks :)
